"""Theme 3 past-paper index (Papers 1 and 3, 2017 to 2025). Descriptions are paraphrased, not exam wording.
Row: (session, paper, ref, marks, command, spec, chapter, summary, examiner note or "")."""
R = []
def r(*a): R.append(a)

# 2017 June
r("June 2017", 1, "4(a)", 4, "Draw", "3.3.4", "3-3", "Cost and revenue diagram showing how a fall in sales hits a construction-equipment firm's profit", "")
r("June 2017", 1, "5(b)", 2, "Explain", "3.3.2", "3-3", "Fixed costs versus variable costs", "")
r("June 2017", 1, "5(c)", 2, "Calculate", "3.3", "3-3", "Profit per coffee drink from a revenue and cost breakdown chart", "")
r("June 2017", 1, "6(a)", 5, "Explain", "3.4.4", "3-4", "Why the four-firm concentration ratio in supermarkets changed over five years", "")
r("June 2017", 1, "6(b)", 12, "Discuss", "3.4.6", "3-4", "How supermarket buyer power affects food suppliers and consumers", "")
r("June 2017", 1, "6(c)", 8, "Examine", "3.6.1", "3-6", "Government measures to limit supermarkets' monopsony power", "")
r("June 2017", 1, "6(e)", 15, "Discuss", "3.1.2", "3-1", "Problems two large supermarkets might face if they merged", "")
r("June 2017", 1, "8", 25, "To what extent", "3.2.1", "3-2", "Is revenue maximisation a more realistic objective than profit maximisation? (own industry)", "")
r("June 2017", 3, "2(c)", 12, "Discuss", "3.5.3", "3-5", "Effect of the National Living Wage on firms' profitability, with a cost and revenue diagram", "")
# 2018 June
r("June 2018", 1, "4(a)", 4, "Calculate", "3.2.1", "3-2", "Change in supernormal profit when a business switches from profit to revenue maximisation", "")
r("June 2018", 1, "5(c)", 2, "Calculate", "3.4.4", "3-4", "Five-firm concentration ratio from sales data", "")
r("June 2018", 1, "6(b)", 12, "Discuss", "3.6.1", "3-6", "How effective measures to open up competition in the energy market are likely to be", "")
r("June 2018", 1, "6(c)", 10, "Assess", "3.6.1", "3-6", "Effect of regulating energy suppliers' profits on consumers and suppliers", "")
r("June 2018", 1, "6(e)", 15, "Discuss", "3.5.2", "3-5", "Policies by firms and government to reduce labour immobility", "")
r("June 2018", 1, "8", 25, "Evaluate", "3.4.5", "3-4", "Is one firm's very large market share (smartphones) in the consumer interest? Diagrams expected", "")
r("June 2018", 3, "1(a)", 5, "Explain", "3.4", "3-4", "Market structure that best describes UK branded coffee shops, using a share chart", "")
r("June 2018", 3, "1(b)", 12, "Discuss", "3.4.4", "3-4", "Price and non-price strategies a coffee chain might use to raise profit", "")
r("June 2018", 3, "1(d)", 25, "Evaluate", "3.1.2", "3-1", "Factors affecting whether a coffee chain expands into a particular country", "")
# 2019 June
r("June 2019", 1, "3(b)", 4, "Draw", "3.4.3", "3-4", "Long-run equilibrium diagram for a monopolistically competitive firm", "")
r("June 2019", 1, "4(b)", 4, "Calculate", "3.3.2", "3-3", "Total costs of a firm from the data given", "")
r("June 2019", 1, "6(b)", 8, "Examine", "3.1.2", "3-1", "Benefits to consumers of two telecoms firms integrating", "")
r("June 2019", 1, "6(d)", 12, "Discuss", "3.3.4", "3-3", "One reason for a firm's rising profit, with a cost and revenue diagram", "")
r("June 2019", 1, "6(e)", 15, "Discuss", "3.6.1", "3-6", "Government methods of protecting consumers in utilities markets", "")
r("June 2019", 1, "7", 25, "Evaluate", "3.5.3", "3-5", "Why wage differences exist in the UK labour market (own industry)", "")
r("June 2019", 1, "8", 25, "Evaluate", "3.4.4", "3-4", "Why some firms collude (own industry; a truck-maker cartel is the prompt)", "")
r("June 2019", 3, "1(a)", 5, "Explain", "3.4.4", "3-4", "Meaning of a 'highly concentrated' market, using a crisps market chart", "")
r("June 2019", 3, "1(c)", 12, "Discuss", "3.4.4", "3-4", "Effects on firms of cutting prices in an oligopoly, using game theory", "")
r("June 2019", 3, "2(b)", 8, "Examine", "3.1.1", "3-1", "Reasons, other than finance, why most manufacturers in a developing country stay small", "")
# 2020 Oct
r("Oct 2020", 1, "4(a)", 2, "Explain", "3.3.2", "3-3", "What happens to total cost beyond a given output on a cost chart", "Many scored 0 or 1 by only saying costs rise. The second mark is for saying total cost rises faster than output, which links to diminishing marginal returns.")
r("Oct 2020", 1, "4(c)", 2, "Calculate", "3.3.2", "3-3", "Total daily cost from AVC as a percentage of price, plus fixed cost", "Mostly well done. Marks were lost by calculating something other than what was asked (total cost, not total variable cost).")
r("Oct 2020", 1, "5(a)", 2, "Explain", "3.1.1", "3-1", "Why a tea-room business has stayed small", "Any sensible reason with a linked development earns both marks. A longer answer scores no more.")
r("Oct 2020", 1, "5(b)", 2, "Explain", "3.1.2", "3-1", "Why a firm's earlier expansion counts as organic growth", "Organic means internal growth from reinvested profit with no merger. Some students had not revised it.")
r("Oct 2020", 1, "6(c)", 10, "Assess", "3.6.1", "3-6", "Whether full nationalisation of the railways would protect employees", "The question was about employees. Weaker answers discussed nationalisation in general. Lack of evaluation was the common gap.")
r("Oct 2020", 1, "6(d)", 12, "Discuss", "3.4.5", "3-4", "Whether the rail network is a natural monopoly", "It asks about a natural monopoly, not just a monopoly. Define it, then use the data. A diagram was not required.")
r("Oct 2020", 1, "6(e)", 15, "Discuss", "3.4.5", "3-4", "Benefits of price discrimination to rail passengers (diagram)", "A correct price discrimination diagram was the dividing line. A judgement was not required.")
r("Oct 2020", 1, "8", 25, "Evaluate", "3.4.6", "3-4", "Costs of a monopsony in a market such as book retailing", "Weaker answers treated the firm as a monopoly seller. Good answers used monopsony ideas, even without a diagram.")
r("Oct 2020", 3, "2(c)", 12, "Discuss", "3.3.4", "3-3", "Why many high street retailers are closing branches, with a cost and revenue diagram", "A diagram with explanation earned top-level marks. Evaluation was often generic.")
# 2021 Nov
r("Nov 2021", 1, "1(b)", 4, "Explain", "3.5.1", "3-5", "Effect of migration on engineers' wage level (labour market)", "")
r("Nov 2021", 1, "3(a)", 4, "Draw", "3.4.5", "3-4", "Complete a third-degree price discrimination diagram showing price and profit in each sub-market", "")
r("Nov 2021", 1, "4(a)", 2, "Calculate", "3.3.1", "3-3", "Total revenue from theatre ticket sales at full capacity", "")
r("Nov 2021", 1, "4(b)", 2, "Calculate", "3.3.2", "3-3", "Subsidy needed for a production to cover all its costs", "")
r("Nov 2021", 1, "5(a)", 4, "Draw", "3.4.2", "3-4", "Long-run diagrams for a competitive market and a typical firm in it", "")
r("Nov 2021", 1, "6(a)", 5, "Explain", "3.3.2", "3-3", "Diminishing marginal productivity and airline cabin-crew staffing", "")
r("Nov 2021", 1, "6(c)", 10, "Assess", "3.1.1", "3-1", "Whether a travel firm's failure was caused by the principal-agent problem", "")
r("Nov 2021", 1, "6(d)", 12, "Discuss", "3.3.4", "3-3", "Government subsidy to stop a failing firm reaching its shut-down point", "")
r("Nov 2021", 1, "6(e)", 15, "Discuss", "3.4.4", "3-4", "A package-holiday firm's decision to raise prices after a rival's collapse", "")
r("Nov 2021", 1, "7", 25, "Evaluate", "3.5.3", "3-5", "Disadvantages of a big rise in the national living wage in a labour market such as social care", "")
r("Nov 2021", 1, "8", 25, "Evaluate", "3.4", "3-4", "Consequences for business decisions of rising market concentration", "")
r("Nov 2021", 3, "1(a)", 5, "Explain", "3.4", "3-4", "Market structure of the UK hand car wash industry", "")
r("Nov 2021", 3, "1(c)", 12, "Discuss", "3.5.3", "3-5", "Effects of changing migration on firms, with a labour market diagram", "")
r("Nov 2021", 3, "1(d)", 25, "Evaluate", "3.4", "3-4", "Factors that determine the number of firms in an industry", "")
r("Nov 2021", 3, "1(e)", 25, "Evaluate", "3.6", "3-6", "Effects of more government intervention in an industry", "")
r("Nov 2021", 3, "2(c)", 12, "Discuss", "3.3", "3-3", "Effect of investment in new technology on firms' profitability, with a cost and revenue diagram", "")
# 2022 June
r("June 2022", 1, "4(a)", 4, "Draw", "3.4.4", "3-4", "Simple two-firm, two-outcome game theory model to show why suppliers might collude", "")
r("June 2022", 1, "5(b)", 2, "Explain", "3.3.3", "3-3", "One internal economy of scale from a car-company merger", "")
r("June 2022", 1, "5(c)", 2, "Explain", "3.6.1", "3-6", "A concern competition authorities may have about the merger", "")
r("June 2022", 1, "6(a)", 5, "Calculate", "3.4.4", "3-4", "Three-firm concentration ratio from a market-share chart", "")
r("June 2022", 1, "6(c)", 10, "Assess", "3.2.1", "3-2", "Whether profit maximisation is the objective of coffee-shop owners", "")
r("June 2022", 1, "6(d)", 12, "Discuss", "3.3", "3-3", "Effect of rising costs on coffee shops' profit, with a cost and revenue diagram", "")
r("June 2022", 1, "6(e)", 15, "Discuss", "3.4.7", "3-4", "Whether the coffee-shop market is contestable", "")
r("June 2022", 1, "7", 25, "Evaluate", "3.4.5", "3-4", "Whether a monopoly is likely to operate efficiently", "")
r("June 2022", 1, "8", 25, "Evaluate", "3.5.2", "3-5", "Factors influencing the supply of labour in an occupation of your choice", "")
r("June 2022", 3, "1(c)", 12, "Discuss", "3.1.2", "3-1", "Effects of increasing integration in the food-delivery market", "")
r("June 2022", 3, "1(e)", 25, "Evaluate", "3.5.3", "3-5", "Effects of significant minimum wage rises (restaurants or food delivery)", "")
# 2023 June
r("June 2023", 1, "3(b)", 4, "Draw", "3.4.3", "3-4", "Short-run, loss-making equilibrium diagram for a monopolistically competitive baker", "")
r("June 2023", 1, "5(b)", 4, "Explain", "3.4.6", "3-4", "Why public-sector nurses' pay rose less than private-sector pay, using monopsony", "")
r("June 2023", 1, "6(a)", 5, "Explain", "3.4", "3-4", "Market structure of UK online streaming, using a share chart", "")
r("June 2023", 1, "6(e)", 15, "Discuss", "3.4.5", "3-4", "Effect of price discrimination on a firm's profits (diagram)", "")
r("June 2023", 3, "1(c)", 12, "Discuss", "3.3", "3-3", "Effect of a gas price rise on a firm that uses a lot of gas, with a cost and revenue diagram", "")
r("June 2023", 3, "2(b)", 8, "Examine", "3.1.1", "3-1", "Reasons retailers on the high street tend to remain small", "")
r("June 2023", 3, "2(c)", 12, "Discuss", "3.4.4", "3-4", "Price and non-price competition methods for high street firms", "")
r("June 2023", 3, "2(e)", 25, "Evaluate", "3.5", "3-5", "Effects of labour shortages in the UK or another developed economy", "")
# 2024 June
r("June 2024", 1, "3(a)", 4, "Draw", "3.2.1", "3-2", "Cost and revenue diagram contrasting profit maximisation and revenue maximisation", "")
r("June 2024", 1, "5(a)", 4, "Explain", "3.4", "3-4", "Market structure of UK mortgage lending, using a market-share chart", "")
r("June 2024", 1, "6(b)", 8, "Examine", "3.5.2", "3-5", "Two factors affecting labour supply in the electronics industry", "")
r("June 2024", 1, "6(c)", 10, "Assess", "3.3.3", "3-3", "Whether electronics firms benefit from economies of scale", "")
r("June 2024", 1, "6(d)", 12, "Discuss", "3.6.1", "3-6", "Competition authority concerns about a proposed merger", "")
r("June 2024", 1, "7", 25, "Evaluate", "3.3", "3-3", "Effects of rising energy bills on the hotel industry (costs and profit)", "")
r("June 2024", 1, "8", 25, "Evaluate", "3.4.7", "3-4", "Level of contestability in the fragrance industry or another", "")
r("June 2024", 3, "1(c)", 12, "Discuss", "3.1.2", "3-1", "Constraints on growth for energy suppliers to households", "")
r("June 2024", 3, "1(d)", 25, "Evaluate", "3.5", "3-5", "Factors behind gender pay gaps in the oil and gas industry", "")
# 2025 June
r("June 2025", 1, "1(a)", 4, "Calculate", "3.2.1", "3-2", "Change in supernormal profit moving from revenue to profit maximisation", "")
r("June 2025", 1, "5(a)", 4, "Draw", "3.5.3", "3-5", "Labour market diagram for a rise in the National Minimum Wage in hospitality", "")
r("June 2025", 1, "6(b)", 8, "Examine", "3.5.1", "3-5", "Two effects of automation on the demand for labour", "")
r("June 2025", 1, "6(d)", 10, "Assess", "3.4.7", "3-4", "Whether the video-game development market is contestable", "")
r("June 2025", 1, "6(e)", 15, "Discuss", "3.1.2", "3-1", "Benefits of mergers for a large firm such as Microsoft", "")
r("June 2025", 3, "1(b)", 8, "Examine", "3.5", "3-5", "Reasons supermarket wages exceed the National Minimum Wage", "")
r("June 2025", 3, "1(c)", 12, "Discuss", "3.4.4", "3-4", "Whether similar petrol prices at supermarkets signal collusion (game theory)", "")
